CLUSTAL multiple sequence alignment by MUSCLE (3.8)


NP_001071605.1      ------------------------------------------------------------
AAI16898.1          ---------------------------------------------------------MSL
XP_021059770.2      MPESTTGVCPMSMKLKTSRCPCVFLSLNKLCYYLCRFYGASGSGAGLLAKHSSLCILMSL
AHC06151.1          ---------------------------------------------------------MSL
CAH6826915.1        ---------------------------------------------------------MSL
                                                                                

NP_001071605.1      -MKPTPKLLAGLILLILCVVGCSGQHWSYGLRPGGKRNAENVIDSFQEIAKEVDQPVEPK
AAI16898.1          RVDMILKLMAGILLLTVCLEGCSSQHWSYGLRPGGKRNTEHLVESFQEMGKEVDQMAEPQ
XP_021059770.2      RMDMILKLMAGVLLLTVCLEGCSSQHWSYGLRPGGKRNTEHLGDSFQEMGKEVDQMAEPQ
AHC06151.1          RVEMIPKLTAVVVLLSLCLEGCSSEHWSYGLRPGGKRNAEHLSDSFQEMGKEVDQLAEPQ
CAH6826915.1        RVEMIRKLTAAVLLLSLCLEGCSSQHWSYGLRPGGKRNAEHLGDSFQEMGKDVDQLAEPQ
                     :.   ** * ::** :*: ***.:*************:*:: :****:.*:*** .**:

NP_001071605.1      CCGCIVHQSHSPLRDLKAALESLIEEETGQRKI
AAI16898.1          HFECTVHWPRSPLRDLRGALESLIEEEARQKKM
XP_021059770.2      HFECTVHWPRSPLRDLRGALESLIEEEARQKKM
AHC06151.1          HFECTVRWPRSPLRDLRGALESLIEEEARQKKM
CAH6826915.1        HFECTVHWPRSPLRDLRGALESLIEEETRQKKM
                       * *....******..*********: *.*:
